version: '3.8'

services:
  app:
    image: php:8.2-apache
    container_name: panicbully_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: panicbully_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: panicbully
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  db_data:
