version: '3.8'

services:
  web:
    build: .
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: panicbully2025!
      MYSQL_DATABASE: panicbully
      MYSQL_USER: root
      MYSQL_PASSWORD: panicbully2025!
    volumes:
      - db_data:/var/lib/mysql
      - ./panicbully.sql:/docker-entrypoint-initdb.d/panicbully.sql

volumes:
  db_data:
